name = "라떼의 스카이블럭"
author = "Jasper"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "963808294dea13617004cf8f06eecf96fd0f1d5ee1a5a1df195c1f7464755637"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
