name = "Classic Mekanism Textures"
filename = "ClassicMekTextures.zip"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/6375/836/ClassicMekTextures.zip"
hash-format = "sha256"
hash = "afe5b4c78bf11001565f09de0c19ba27a072390d984a1dc295ff5ab59556b1c1"

[update.curseforge]
file-id = 6375836
project-id = 1028778
