name = "ATO - All the Ores"
filename = "alltheores-3.2.0_neoforge_1.21.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/7825/464/alltheores-3.2.0_neoforge_1.21.1.jar"
hash-format = "sha256"
hash = "7de4018f8475874347bd8dc5b7551cad80c31446de8daae7c86aee5480f9c80a"

[update.curseforge]
file-id = 7825464
project-id = 405593
