name = "Almost Unified"
filename = "almostunified-neoforge-1.21.1-1.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/8127/603/almostunified-neoforge-1.21.1-1.4.2.jar"
hash-format = "sha256"
hash = "65202adf4dccf7b3033537e539e23eccc541c6a15ad88d87fa1c5a09ceb3359f"

[update.curseforge]
file-id = 8127603
project-id = 633823
