name = "Apothic Spawners"
filename = "ApothicSpawners-1.21.1-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/8469/405/ApothicSpawners-1.21.1-1.4.0.jar"
hash-format = "sha256"
hash = "f0cbc52ad606997789c36fac94ae651ab7e2e21c841e26a952c64041cad9cdbe"

[update.curseforge]
file-id = 8469405
project-id = 986583
