name = "Ars Ocultas"
filename = "ars_ocultas-1.21.1-2.6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/8586/886/ars_ocultas-1.21.1-2.6.1.jar"
hash-format = "sha256"
hash = "64cb7b7c29964712ec2d0d4bbf6d33a6a7250759c1fdff2fa62831159c10b963"

[update.curseforge]
file-id = 8586886
project-id = 907843
