name = "Ars Caelum"
filename = "ars_caelum-1.21.1-3.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/6172/865/ars_caelum-1.21.1-3.0.0.jar"
hash-format = "sha256"
hash = "3a0a08e62b26f73d92fc8191086760a4d646290ee1cd7cc25003eec4d4fc9d71"

[update.curseforge]
file-id = 6172865
project-id = 821651
