name = "Botany Pots"
filename = "botanypots-neoforge-1.21.1-21.1.44.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/8243/851/botanypots-neoforge-1.21.1-21.1.44.jar"
hash-format = "sha256"
hash = "45b23ac195511f724f62ab5f0c2d7a1c2c2403ff324a7403a1142e28a7d65edd"

[update.curseforge]
file-id = 8243851
project-id = 353928
