name = "Common Capabilities"
filename = "commoncapabilities-1.21.1-neoforge-2.11.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/8247/199/commoncapabilities-1.21.1-neoforge-2.11.5.jar"
hash-format = "sha256"
hash = "45d352af870c63ec8e131f133d25602799b885eafb38922a9b6b66daea152eba"

[update.curseforge]
file-id = 8247199
project-id = 247007
