name = "Create Crafts & Additions"
filename = "createaddition-1.6.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/8188/476/createaddition-1.6.0.jar"
hash-format = "sha256"
hash = "41876c3780b70365a1848994d146a73423cc19fbe86485885795d9e7d855e7e9"

[update.curseforge]
file-id = 8188476
project-id = 439890
