name = "Dark Mode Everywhere"
filename = "darkmodeeverywhere-1.21-1.3.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/6470/153/darkmodeeverywhere-1.21-1.3.5.jar"
hash-format = "sha256"
hash = "482b5b714bfe3efc883c1e5f0234014c9c6db50c8a6d512ee275c46c8382a174"

[update.curseforge]
file-id = 6470153
project-id = 574123
