name = "Expanded AE"
filename = "expandedae-2.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/6910/849/expandedae-2.1.1.jar"
hash-format = "sha256"
hash = "f39c0eb9c6271f54a44ffee092a29520f53000d1005849e6afada3ad9dffba14"

[update.curseforge]
file-id = 6910849
project-id = 1213351
