name = "Explorer's Compass"
filename = "ExplorersCompass-1.21.1-3.4.0-neoforge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/7892/943/ExplorersCompass-1.21.1-3.4.0-neoforge.jar"
hash-format = "sha256"
hash = "71e7b47bd88c9c210d7c06fe5276736fc2e225e869778216537d584e6d1faf24"

[update.curseforge]
file-id = 7892943
project-id = 491794
