name = "FTB Essentials (Forge & Fabric)"
filename = "ftb-essentials-neoforge-2101.1.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/8442/866/ftb-essentials-neoforge-2101.1.10.jar"
hash-format = "sha256"
hash = "a61de1b883ec9d6d652276f453e8e60b18bd315fef8c62f21d6545260d526587"

[update.curseforge]
file-id = 8442866
project-id = 410811
