name = "Functional Storage"
filename = "functionalstorage-1.21.1-1.5.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/8459/97/functionalstorage-1.21.1-1.5.8.jar"
hash-format = "sha256"
hash = "e3e7368c28a24e7de5b877988aa92cc94ca7417c8f60b7d28e7f584a94a51147"

[update.curseforge]
file-id = 8459097
project-id = 556861
