name = "Inventory Tweaks - ReFoxed"
filename = "invtweaks-1.21.1-1.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/6407/807/invtweaks-1.21.1-1.3.2.jar"
hash-format = "sha256"
hash = "ceb5b20a43ca1c5bd707f60bb5d5fa61099c7a7ba50b19f6bddfe93f1ca0073c"

[update.curseforge]
file-id = 6407807
project-id = 976858
