name = "KeybindsPurger"
filename = "KeybindsPurger-1.4.0-neoforge-1.21.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/7733/186/KeybindsPurger-1.4.0-neoforge-1.21.1.jar"
hash-format = "sha256"
hash = "e4e7842a26d11ea2470d23ab2600114b4bace9b74f6ea3478b933ceb24f2479b"

[update.curseforge]
file-id = 7733186
project-id = 1099143
