name = "Kotlin for Forge"
filename = "kotlinforforge-5.12.0-all.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/8335/665/kotlinforforge-5.12.0-all.jar"
hash-format = "sha256"
hash = "095aed94f21b4e55895b21ea957750ae3ab829fbcfc6d3c66a3489f5f1128d46"

[update.curseforge]
file-id = 8335665
project-id = 351264
