name = "Mystical Agriculture Tiered Crystals"
filename = "matc-1.7.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/5863/210/matc-1.7.1.jar"
hash-format = "sha256"
hash = "d54dd6ee1925c0103bca13842a229b0a7851c4658fb2f0cd3c8b46fb9dd532a2"

[update.curseforge]
file-id = 5863210
project-id = 299045
