name = "Modern Industrialization"
filename = "Modern-Industrialization-2.5.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/8597/392/Modern-Industrialization-2.5.6.jar"
hash-format = "sha256"
hash = "9d7e5384ff5ec990823863b4a7e4f5aa8ad8883c9f96145867db904bd651f3f0"

[update.curseforge]
file-id = 8597392
project-id = 405388
