name = "Moonlight Lib"
filename = "moonlight-neoforge-1.21.1-3.0.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/8156/754/moonlight-neoforge-1.21.1-3.0.16.jar"
hash-format = "sha256"
hash = "6677fa40f61b507bf6b22c882a169049ba7de7d5546d3374903cf0a43d761fed"

[update.curseforge]
file-id = 8156754
project-id = 499980
