name = "NeoAuth"
filename = "NeoAuth-1.21.1-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/7069/504/NeoAuth-1.21.1-1.0.1.jar"
hash-format = "sha256"
hash = "cd945b64ba805e42ca0b039ba0df69eb087182988ebc35d0bde8e7df400eda72"

[update.curseforge]
file-id = 7069504
project-id = 1140741
