name = "Occultism"
filename = "occultism-1.21.1-neoforge-1.224.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/8745/224/occultism-1.21.1-neoforge-1.224.4.jar"
hash-format = "sha256"
hash = "b82a5ed9468d64beac21139aff5f15db287104668d8e98db7eafc042c9a79178"

[update.curseforge]
file-id = 8745224
project-id = 361026
