name = "Pipez Lag Fix"
filename = "pipezlagfix-1.21.1-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/8113/984/pipezlagfix-1.21.1-1.1.0.jar"
hash-format = "sha256"
hash = "1d416bb28a6b6cba1489a2dd3beb77d329b1d797db8ec239d81885e2ef277051"

[update.curseforge]
file-id = 8113984
project-id = 1446489
