name = "Productive Bees"
filename = "productivebees-1.21.1-13.13.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/8022/994/productivebees-1.21.1-13.13.5.jar"
hash-format = "sha256"
hash = "9d48d198bc6eacf3b7729f4d60b91e661cfa15d105264ba225dee87b1d547ba1"

[update.curseforge]
file-id = 8022994
project-id = 377897
