name = "Silent's Gems"
filename = "silentgems-1.21.1-neoforge-5.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/7512/691/silentgems-1.21.1-neoforge-5.1.3.jar"
hash-format = "sha256"
hash = "595eef36895991a5a2199e6b6bfb1b55cabb3f7a9e808d396697aec1fe4fdc3d"

[update.curseforge]
file-id = 7512691
project-id = 220311
