name = "Supplementaries"
filename = "supplementaries-neoforge-1.21.1-3.6.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/8194/573/supplementaries-neoforge-1.21.1-3.6.7.jar"
hash-format = "sha256"
hash = "352502e94b84f0e00ab29c16eca31c95fa9a37a4c38ec0ef7b71a4576dfddfa8"

[update.curseforge]
file-id = 8194573
project-id = 412082
