name = "Time in a Bottle"
filename = "tiab-neoforge-6.5.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/7555/622/tiab-neoforge-6.5.4.jar"
hash-format = "sha256"
hash = "0beb4ff1d81facfe9039e8d657a75836d1e8c13c137c90b491cc07e763f26325"

[update.curseforge]
file-id = 7555622
project-id = 895919
