name = "Zume"
filename = "zume-1.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/7983/502/zume-1.2.2.jar"
hash-format = "sha256"
hash = "c33b99e8976dfeb0aeb1afcc2ad8e65c7310532ae5ccc38c75317d672dc95e6f"

[update.curseforge]
file-id = 7983502
project-id = 927564
